---
name: "tagged-release"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: create VERSION file
        run: |
          echo -n ${{ steps.get_version.outputs.version }} > cmd/VERSION
      - name: Test all packages except csvgen
        run: |
          go test $(go list ./... | grep -v csvgen)

  tagged-release:
    name: "Tagged Release"
    needs: test
    runs-on: "macos-latest"
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x
      - name: Install make
        run: brew install make
      - name: Install cross-compiler
        run: brew install FiloSottile/musl-cross/musl-cross
      - uses: actions/checkout@v2
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: Build
        run: "gmake VERSION=${{ steps.get_version.outputs.version }}"
      - name: Put version number in wrgld installer
        uses: bluwy/substitute-string-action@v1
        id: sub-wrgld-installer
        with:
          _input-file: "./.github/workflows/template/install.sh"
          _output-file: "./build/install.sh"
          _format-key: "%%key%%"
          version: "${{ steps.get_version.outputs.version }}"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/*.tar.gz
            build/install.sh
